
* users
  - chown
    chown -R user:group dir
  - adduser
    
  - sudo -u user cmd
  

* development
** ldap
** /etc/ld.so.conf
* ld
  - /etc/ld.so.conf
  - ldconfig
    since stale ld.so.cache, run ldconfig to update it.
** ldd
** elf
   Executable and Linkable Format
   if ldd doesn't work, use readelf.
   : readelf -d executable | grep NEEDED

* ssh
  add your public key to target user's ~/.ssh/authorized_keys,
  then you can ssh the target user without authorization, or
  : ssh-copy-id -i ~/.ssh/id_rsa.pub usr@host
  what if the target user change its password?
  |                       |   |
  |-----------------------+---|
  | ssh user@host -t 'ls' |   |
  |                       |   |
  |                       |   |
  |                       |   |
  
* grep
  : echo -e '123\n\d+' | grep -P '\d+'
  '\d' is not in grep's regrex, add -P to use perl regex. or use
  : [[:digit:]]
  
* intersection between two files
  : sort a.txt b.txt | uniq -d  # make sure a.txt, b.txt don't have duplicate lines
  : grep -f a.txt b.txt  # slower than the above one
* FAQ
** GPG Error on Update
#+BEGIN_EXAMPLE
sudo apt-get clean
cd /var/lib/apt
sudo mv lists lists.old
sudo mkdir -p lists/partial
sudo apt-get clean
sudo apt-get update
#+END_EXAMPLE
