
- find all port that pid is listening
- find files with modifcation time before 3 days ago
- parent process send data to child process
- find data package from one ip port
- RAID5
- nmap, zmap
- xss
- keep-alive
- 竞赛树, 胜者树
- local sensitive hashing
- x permission in directory
- manacher algorithm to find longest palindrome substring in linear time
  - extra 
    insert special char (like #) in betwen letters, both palindromes of odd and
    even lengths are handled graciously
    : abaaba
    : #a#b#a#a#b#a#

- consistent hash in p2p, distributed db
  distributed hash table
- http://en.wikipedia.org/wiki/Reservoir_sampling
- outner join
- voronoi
- how is C++ std::string::find implements? 
  kmp or brute force?
- signed cast to unsigned?
- hbase corprocsser
- threaded binary tree, morris
- LinkedHashMap
  will iterate *in the order* in which the entries were put into the map
- LRUCache
  O(1) is implemented with ArrayList + HashMap
  - LinkedHashMap inherited from HashMap LinkedHashMap will iterate in the order
    in which the entries were put into the map. However, not thread-safe.
    ConcurrentHashMap
  Another implemention is use Hashmap + Sortedmap, where the sortedmap store
  each key's last accesstime
  https://github.com/twitter/util/blob/master/util-collection/src/main/scala/com/twitter/util/ImmutableLRU.scala
  : cache: Map[K,(Long,V)], ord: SortedMap[Long,K]
  - in java, inherient LinkedHashMap, and override `removeEldestEntry`

- memory pool
- translation lookaside buffer (TLB)
  TLB tremble
- closest pair of points 
- security testing
  - sql injection
  - cross-site scripting(XSS)
    http://www.acunetix.com/websitesecurity/cross-site-scripting/
- LCA
- coherent hashing
- log structured merge-stree
  used in leveldb
- tcp 
  - Congestion Control, AIMD (Additive increase/multiplicative decrease)
- Bit Torrent protocol 
- fork

* multithread
  wait & notify

* why zookeepr?
  - paxos algorithm

* load balance
  weighted Round Robin

- algorithm on strings & sequences

* hash
  - open addressing
  - re-hash
  - chaining
  - sth
    unordered_set, rehashing occurs only if the new number of elements is equal
    to or greater than =max_load_factor()*bucket_count()=
  - rolling hash function, one in which if a character is deleted from the
    front of the string, and another added to the end, the new hash code can be
    computed in O(1) time.
  - is MD5 a rolling hash?
* difference between iterable and iterator

* mathematics
  - Taylor series
  - 同余(same remainder?)
  - Possion Distribution
  - 允许重复的组合（有重集组合？）
    x1 + x2 + ... + xk = r, r >= 0, xi >=0
    => C(r + k - 1, r)
    即k-1个0将r个1分开的方案数，或者说r + k - 1个位置选k-1个来放0
    hdu 1294 m个位置，每个位置有k种方案，k^m/m!,这样是有问题的！
    应该建模为：k种方案，每种方案选xi个，x1 + x2 + ... + xk = m
  - 有重集排列
    n!/(n1!n2!..nk!)
    两种理解，一种是先当成无重集排列，再除以每个重集的排列；一种是用组合来解释，
    n个位置选n1个放1，剩下的n-n1个选n2个放2。。。
  - harmonic series
* others
  - what if query are enormoous?

* system
  - when crawling, how to avoid the inifite loop.
    Different url may have same content!
  - NIO, epoll
  - 文件队列
  - id generator
    - request, return the minimum available id
    - release
    - single machine approach, use map to store (x, k), means [x, x+k) is avaiable
    - what about multi-thread solution?
* C++
- smart pointer
* Data Structure
- heap
- BST
- B-tree, B+tree
  Indexing block-oriented storage.
  B+ trees don't have data associated with interior nodes while B trees contain
  data with each key.
  BTree+ stored keys (and not values) are stored in the intermediate nodes. This
  would mean that you would need fewer intermediate node blocks and would
  increase the likelihood of a cache hit.
  B+Trees are much easier and higher performing to do a full scan, as in look at every piece of data that the tree indexes, since the terminal nodes form a linked list.
  B-Trees on the other hand can be faster when you do a seek (looking for a specific piece of data by key) especially when the tree resides in RAM or other non-block storage.
* streaming calculation
  - storm vs. MQ ?
* spark, RDD(resilient distirbuted data)

* design patterns
- visitor    


- bitcount without loop
  http://graphics.stanford.edu/~seander/bithacks.html#CountBitsSetParallel
```
int bitcount(int x) {  
  x = x - ((x >> 1) & 0x55555555);  
  x = (x & 0x33333333) + ((x >> 2) & 0x33333333);  
  x = (x + (x >> 4)) & 0x0F0F0F0F;  
  x = x + (x >> 8);  
  x = x + (x >> 16);  
  return x & 0x0000003F;  
}
```
