* query
: db.collection.find({field:null})
: db.collection.find({field:{$exists: false}})
update a field, rather replace the record
: db.collection.update({id:123}, {$set:{date:ISODate()}}}
: db.collection.update({id:123}, {$unset:{date:1}})  # remove a field
count
$setOnInsert
findAndModify

: db.collection.ensureIndex({a:1, b:})
Can I create serveral index with common part?
{a, b, c}, {a, e}


mongodb support tag excellently ?

* Query Selectors
** Comparison
   http://docs.mongodb.org/manual/reference/operator/#query-selectors
   | name | description |
   |------+-------------|
   | $all |             |
   | $gt  |             |
   | $gte |             |
   | $in  |             |
   | $lt  |             |
   | $lte |             |
   | $ne  |             |
   
   : db.col.find({field: {$lt:1234}})

* Date
  : Date()  // return the current date as a string
  : new Date()  // return an ISODate object
  : [new] ISODate()  // return an ISODate object
  : var now = Date() - 0
  : new Date(now + 1000 * 10)  // 10s later

  ISODate can cast to Date object in java
  
* js
  store javascript into =db.system.js=
  http://docs.mongodb.org/manual/tutorial/store-javascript-function-on-server/
* auto increment
  http://docs.mongodb.org/manual/tutorial/create-an-auto-incrementing-field/

* others
  mongodb has a memory-map engine, reside data in memory.
* import & export
  : mongoexport -d test -c records -q "{ a: { \$gte: 3 } } }" --out exportdir/myRecords.json
  : mongoimport -d test -c records --file  exportdir/myRecords.json
* tips
  - Do not index your collection before inserting, as inserts modify the index which is an overhead. Insert everything, then create index .
  - instead of "save" , use mongoDB "batchinsert" which can insert many records in 1 operation. So have around 5000 documents inserted per batch. You will see remarkable performance gain .
    see the method#2 of insert here, it takes array of documents to insert instead of single document. Also see the discussion in this thread. And if you want to benchmark more. This is just a guess, try using a capped collection of a predefined large size to store all your data. Capped collection without index has very good insertion performance.

