
While streamming use stdin/stdout, pipes use *socket* to communicate.

use java RecordReader, RecordWriter, rather than write them by
yourself.

: -Dhadoop.pipe.java.

* build
  The library in ${HADOOP_HOME}/c++/Linux-amd64-64/lib may not work!
  Need to build native library. [[http://guoyunsky.iteye.com/blog/1709654]]
  
  #+BEGIN_SRC shell
  $ cd src/c++/utils/
  $ ./configure & make install
  $ cd src/c++/pipes/
  $ ./configure & make install
  #+END_SRC
  
  after that, you'll see this generate directories in src/c++/install/
  install/
  ├── include
  │   └── hadoop
  │       ├── Pipes.hh
  │       ├── SerialUtils.hh
  │       ├── StringUtils.hh
  │       └── TemplateFactory.hh
  └── lib
      ├── libhadooppipes.a
      └── libhadooputils.a


  note:
  - if error occures when configure c++/pipes:
    : ./configure: line 302: return: please: numeric argument required
    modify configure according to http://hadoop.illecker.at/?p=206
    #+BEGIN_SRC shell
    # as_fn_set_status STATUS
    # -----------------------
    # Set $? to STATUS, without forking.
    as_fn_set_status ()
    {
    if echo $1 | egrep -q '^[0-9]+$'; then // $1 number check
      return $1
    fi
    } # as_fn_set_status
    # as_fn_exit STATUS
    # -----------------
    # Exit the shell with STATUS, even in a "trap 0" or "set -e" context.
    as_fn_exit ()
    {
      set +e
      as_fn_set_status $1
    if echo $1 | egrep -q '^[0-9]+$'; then // $1 number check
      exit $1
    fi
    } # as_fn_exit
    #+END_SRC
  - if the following error occur when make install pipes:
    : impl/HadoopPipes.cc:1049:16: error: ‘sleep’ was not declared in this scope
    add #incldue "unistd.h" to src/c++/pipes/impl/HadoopPipes.cc
  
* compile

  : ${HADOOP_HOME}/c++/Linux-amd64-64/include/
  : ${HADOOP_HOME}/c++/Linux-amd64-64/lib
  : g++ wordcount-simple.cc -Iinclude -Llib -lhadooppipes  -lhadooputils -lpthread -lssl -lpthread -lcrypto


* something
  - if you get 
    
    http://hadoop.illecker.at/?p=206


* pipes
  - program xxx is same as -Dhadoop.pipes.executable=xxx


* reference
[[http://dongxicheng.org/mapreduce/hadoop-pipes-architecture/]]
[[http://cs.smith.edu/dftwiki/index.php/Hadoop_Tutorial_2.2_--_Running_C%2B%2B_Programs_on_Hadoop]]


